#!/usr/bin/env bash
# Build the process-monitor script from component files.

output_filename=process-monitor
head=head
module1=ConstraintManager
module2=ProcessConstraint
module3=Configuration
module4=Action
module5=ReportAction
module6=EmailAction
module7=KillAction
module8=FooAction
module_files="$module1.pm $module2.pm $module3.pm $module4.pm $module5.pm"
module_files="$module_files $module6.pm $module7.pm"
main=main.pm

{
	cat $head
	for f in $module_files; do
	awk '/^[0-9];$/ {next} {print}' $f
	done
} >$output_filename
chmod +x $output_filename
awk "/use $module1/ {next}
     /use $module2/ {next}
     /use $module3/ {next}
     /use $module4/ {next}
     /use $module5/ {next}
     /use $module6/ {next}
     /use $module7/ {next}
#     /use $module8/ {next}
	 {print}
" $main >> $output_filename
